[build]
  command = "gatsby build"
  functions = "netlify/functions"
  base = ""
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-gatsby"
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false